export const APPEAL_LIST_REQUEST = 'APPEAL_LIST_REQUEST';
export const APPEAL_LIST_SUCCESS = 'APPEAL_LIST_SUCCESS';
export const APPEAL_LIST_FAIL = 'APPEAL_LIST_FAIL';

export const APPEAL_DETAILS_REQUEST = 'APPEAL_DETAILS_REQUEST';
export const APPEAL_DETAILS_SUCCESS = 'APPEAL_DETAILS_SUCCESS';
export const APPEAL_DETAILS_FAIL = 'APPEAL_DETAILS_FAIL';

export const APPEAL_CREATE_REQUEST = 'APPEAL_CREATE_REQUEST';
export const APPEAL_CREATE_SUCCESS = 'APPEAL_CREATE_SUCCESS';
export const APPEAL_CREATE_FAIL = 'APPEAL_CREATE_FAIL';
export const APPEAL_CREATE_RESET = 'APPEAL_CREATE_RESET';

export const APPEAL_UPDATE_REQUEST = 'APPEAL_UPDATE_REQUEST';
export const APPEAL_UPDATE_SUCCESS = 'APPEAL_UPDATE_SUCCESS';
export const APPEAL_UPDATE_FAIL = 'APPEAL_UPDATE_FAIL';
export const APPEAL_UPDATE_RESET = 'APPEAL_UPDATE_RESET';

export const APPEAL_DELETE_REQUEST = 'APPEAL_DELETE_REQUEST';
export const APPEAL_DELETE_SUCCESS = 'APPEAL_DELETE_SUCCESS';
export const APPEAL_DELETE_FAIL = 'APPEAL_DELETE_FAIL';

export const APPEAL_SUBMIT_REQUEST = 'APPEAL_SUBMIT_REQUEST';
export const APPEAL_SUBMIT_SUCCESS = 'APPEAL_SUBMIT_SUCCESS';
export const APPEAL_SUBMIT_FAIL = 'APPEAL_SUBMIT_FAIL';
export const APPEAL_SUBMIT_RESET = 'APPEAL_SUBMIT_RESET';
