export const UI_SET_NOTIFICATION = 'UI_SET_NOTIFICATION';
export const UI_CLEAR_NOTIFICATION = 'UI_CLEAR_NOTIFICATION';
export const UI_SET_LOADING = 'UI_SET_LOADING';
export const UI_CLEAR_LOADING = 'UI_CLEAR_LOADING';
