import React from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Container,
  Typography,
  Button,
  AppBar,
  Toolbar,
  Stack,
  Divider,
} from '@mui/material';
import { HealthAndSafety as HealthIcon } from '@mui/icons-material';

const TermsOfService = () => {
  const navigate = useNavigate();

  const sections = [
    {
      title: '1. Acceptance of Terms',
      content: `By accessing or using AppealAid's services, website, or applications (collectively, the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the Service. These Terms apply to all visitors, users, and others who access or use the Service.`,
    },
    {
      title: '2. Description of Service',
      content: `AppealAid provides an AI-powered insurance appeal automation platform that assists healthcare providers, billing professionals, and patients in preparing, managing, and tracking insurance claim appeals. The Service includes document processing, AI-generated appeal letters, analytics, and collaboration tools. AppealAid does not provide legal or medical advice. Generated appeal content is intended as a starting point and should be reviewed by qualified professionals before submission.`,
    },
    {
      title: '3. User Accounts',
      content: `You must create an account to use certain features of the Service. You are responsible for safeguarding your account credentials and for all activities that occur under your account. You must provide accurate, current, and complete information during registration. You agree to notify us immediately of any unauthorized use of your account. AppealAid reserves the right to suspend or terminate accounts that violate these Terms.`,
    },
    {
      title: '4. Subscription and Billing',
      content: `Some features of the Service require a paid subscription. By subscribing, you agree to pay the applicable fees as described on our Pricing page. Subscriptions automatically renew unless cancelled before the renewal date. Prices are subject to change with 30 days notice. Refunds are provided in accordance with our refund policy. Free trial periods, if offered, will automatically convert to paid subscriptions unless cancelled.`,
    },
    {
      title: '5. Acceptable Use',
      content: `You agree not to: (a) use the Service for any illegal purpose or in violation of any laws; (b) submit false or misleading information; (c) attempt to gain unauthorized access to the Service or its related systems; (d) use the Service to transmit malware or other harmful code; (e) interfere with or disrupt the Service; (f) scrape, crawl, or use automated means to access the Service without permission; (g) use the Service to generate fraudulent insurance claims or appeals.`,
    },
    {
      title: '6. Intellectual Property',
      content: `The Service and its original content, features, and functionality are owned by AppealAid, Inc. and are protected by copyright, trademark, and other intellectual property laws. Appeal letters and content generated by the Service for your use are licensed to you for the purpose of filing insurance appeals. You retain ownership of all documents and data you upload to the Service.`,
    },
    {
      title: '7. Data Privacy and Security',
      content: `Your privacy is important to us. Our collection and use of personal information is governed by our Privacy Policy. We implement industry-standard security measures to protect your data, including encryption at rest and in transit. For healthcare data, we maintain HIPAA compliance and will execute Business Associate Agreements (BAAs) with Enterprise customers upon request.`,
    },
    {
      title: '8. Disclaimers',
      content: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. AppealAid does not guarantee that any appeal generated through the Service will result in a successful outcome. AI-generated content may contain errors and should be reviewed before use. AppealAid is not a law firm and does not provide legal advice. Use of the Service does not create an attorney-client relationship.`,
    },
    {
      title: '9. Limitation of Liability',
      content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, APPEALAID SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUE, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE SERVICE. Our total liability shall not exceed the amount you paid to AppealAid in the twelve (12) months preceding the claim.`,
    },
    {
      title: '10. Termination',
      content: `We may terminate or suspend your account and access to the Service immediately, without prior notice, if you breach these Terms. Upon termination, your right to use the Service will cease immediately. You may export your data within 30 days of termination. After 30 days, all data associated with your account will be permanently deleted.`,
    },
    {
      title: '11. Changes to Terms',
      content: `We reserve the right to modify these Terms at any time. We will notify you of material changes by email or through the Service at least 30 days before the changes take effect. Your continued use of the Service after changes become effective constitutes acceptance of the revised Terms.`,
    },
    {
      title: '12. Governing Law',
      content: `These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved in the state or federal courts located in Delaware.`,
    },
    {
      title: '13. Contact Information',
      content: `If you have any questions about these Terms, please contact us at:\n\nAppealAid, Inc.\nEmail: legal@appealaid.com\nAddress: 123 Innovation Drive, Suite 400, Wilmington, DE 19801`,
    },
  ];

  return (
    <Box sx={{ bgcolor: '#fff', minHeight: '100vh' }}>
      <AppBar position="fixed" color="inherit" elevation={1} sx={{ bgcolor: 'rgba(255,255,255,0.95)', backdropFilter: 'blur(10px)' }}>
        <Toolbar sx={{ justifyContent: 'space-between', maxWidth: 1200, width: '100%', mx: 'auto' }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, cursor: 'pointer' }} onClick={() => navigate('/landing')}>
            <HealthIcon sx={{ color: 'primary.main', fontSize: 32 }} />
            <Typography variant="h5" sx={{ fontWeight: 700, color: 'primary.main' }}>AppealAid</Typography>
          </Box>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
            <Button variant="outlined" onClick={() => navigate('/login')}>Sign In</Button>
            <Button variant="contained" onClick={() => navigate('/register')} disableElevation>Start Free Trial</Button>
          </Box>
        </Toolbar>
      </AppBar>

      <Container maxWidth="md" sx={{ pt: 14, pb: 8 }}>
        <Typography variant="h3" sx={{ fontWeight: 700, mb: 1, fontSize: { xs: '1.8rem', md: '2.4rem' } }}>
          Terms of Service
        </Typography>
        <Typography variant="body2" sx={{ color: 'text.secondary', mb: 4 }}>
          Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </Typography>
        <Divider sx={{ mb: 4 }} />

        <Stack spacing={4}>
          {sections.map((section, index) => (
            <Box key={index}>
              <Typography variant="h6" sx={{ fontWeight: 600, mb: 1 }}>{section.title}</Typography>
              <Typography variant="body1" sx={{ color: 'text.secondary', lineHeight: 1.8, whiteSpace: 'pre-line' }}>
                {section.content}
              </Typography>
            </Box>
          ))}
        </Stack>
      </Container>

      <Box sx={{ py: 4, bgcolor: '#1a1a2e' }}>
        <Container maxWidth="lg">
          <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems="center" spacing={2}>
            <Typography variant="body2" sx={{ color: 'rgba(255,255,255,0.6)' }}>
              &copy; {new Date().getFullYear()} AppealAid, Inc.
            </Typography>
            <Stack direction="row" spacing={3}>
              <Typography variant="body2" sx={{ color: 'rgba(255,255,255,0.6)', cursor: 'pointer', '&:hover': { color: '#fff' } }} onClick={() => navigate('/privacy')}>Privacy Policy</Typography>
              <Typography variant="body2" sx={{ color: 'rgba(255,255,255,0.6)', cursor: 'pointer', '&:hover': { color: '#fff' } }} onClick={() => navigate('/landing')}>Home</Typography>
            </Stack>
          </Stack>
        </Container>
      </Box>
    </Box>
  );
};

export default TermsOfService;
